### ISSUE TITLE
missing dependency at compilation gmock/gmock.h

### ISSUE THREAD

**Issue by nihilman** [khampf/g13#1]
Hello,
Compilation fail because "gmock/gmock.h" was missing on my computer.
Compiling well after manual installation of gmock repository.

**Comment by khampf** [comment]
The gmock part is only needed for the single test that originally came from upstream but which I have since updated to work with my reworked code. I should make the package skip it for now or maybe add more tests and make it a build dependency if the tests were actually useful.

**Comment by khampf** [comment]
I changed the PKGBUILD to only build the two binary targets for now, the test is so incomplete that it can be disabled for now, thus avoiding the dependency on gmock.
