### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by Techjar** [khampf/g13#10]
The old version supported profiles through the bind file. What happened to this feature?

**Comment by khampf** [comment]
Is this essentially the same as issue #11 or did it support profile switching? I suspect the config loader has problems

**Comment by Techjar** [comment]
Currently unclear. I tried feeding the config file in through the pipe, but the `profile` command did not seem to work and all my keys were set to that of the last profile.

**Comment by khampf** [comment]
Fixed by commit 1e80eda
