### ISSUE TITLE
Don't work for me

### ISSUE THREAD

**Issue by nihilman** [khampf/g13#2]
`[nihil@ghost ~]$ systemctl status g13
● g13.service - Logitech G13 daemon
     Loaded: loaded (/usr/lib/systemd/system/g13.service; static; vendor preset: disabled)
     Active: failed (Result: core-dump) since Tue 2020-05-19 20:20:24 CEST; 15s ago
    Process: 2351 ExecStart=/usr/bin/g13d --config /etc/g13/default.bind --pipe_in /run/g13d/g13-0 --pipe_out /run/g13d/g13-0_out & (code=dumped, signal=SEGV)
   Main PID: 2351 (code=dumped, signal=SEGV)

mai 19 20:20:22 ghost systemd[1]: Started Logitech G13 daemon.
mai 19 20:20:22 ghost g13d[2351]: libusb: error [udev_hotplug_event] ignoring udev action bind
mai 19 20:20:24 ghost systemd[1]: g13.service: Main process exited, code=dumped, status=11/SEGV
mai 19 20:20:24 ghost systemd[1]: g13.service: Failed with result 'core-dump'.
[nihil@ghost ~]$ systemctl status g13
● g13.service - Logitech G13 daemon
     Loaded: loaded (/usr/lib/systemd/system/g13.service; static; vendor preset: disabled)
     Active: active (running) since Tue 2020-05-19 20:20:54 CEST; 1s ago
   Main PID: 2422 (g13d)
      Tasks: 2 (limit: 19145)
     Memory: 8.9M
     CGroup: /system.slice/g13.service
             └─2422 /usr/bin/g13d --config /etc/g13/default.bind --pipe_in /run/g13d/g13-0 --pipe_out /run/g13d/g13-0_out &

mai 19 20:20:54 ghost systemd[1]: Started Logitech G13 daemon.
mai 19 20:20:54 ghost g13d[2422]: libusb: error [udev_hotplug_event] ignoring udev action bind
`
trying to unplug-plug several times. Fail every time. Don't know what log I can give you to debug.
Hopefully I have saved the package I have build 4 days ago ;)

**Comment by khampf** [comment]
Let's try running the daemon as the g13 user and adding the debug flag:
`sudo -u g13 /usr/bin/g13d --config /etc/g13/default.bind --pipe_in /run/g13d/g13-0 --pipe_out /run/g13d/g13-0_out --log_level DEBUG`

Capture the output of that and I will try to figure out what's making it crash for you. I could also look at what kernel you use if you run `uname -a`

If all else fails I keep old versions around myself too but it would be better to get a grip on what's going on here.

**Comment by nihilman** [comment]
Hello, here are the infos:
`[nihil@ghost rules.d]$ sudo -u g13 /usr/bin/g13d --config /etc/g13/default.bind --pipe_in /run/g13d/g13-0 --pipe_out /run/g13d/g13-0_out --log_level DEBUG
1589961261 INFO  : g13d v1.0.3-beta-1-g2b39aec-dirty May 19 2020 17:53:15
1589961261 INFO  : Known keys on G13:
1589961261 INFO  : BD DOWN G1 G10 G11 G12 G13 G14 G15 G16 G17 G18 G19 G2 G20 G21 G22 G3 G4 G5 G6 G7 G8 G9 L1 L2 L3 L4 LEFT LIGHT LIGHT2 LIGHT_STATE M1 M2 M3 MISC_TOGGLE MR TOP UNDEF1 UNDEF3
1589961261 INFO  : Known keys to map to:
1589961261 INFO  : 0 1 2 3 4 5 6 7 8 9 A APOSTROPHE B BACKSLASH BACKSPACE C CAPSLOCK COMMA D DELETE DOT DOWN E END ENTER EQUAL ESC F F1 F10 F11 F12 F13 F14 F15 F16 F17 F18 F19 F2 F20 F21 F22 F23 F24 F3 F4 F5 F6 F7 F8 F9 G GRAVE H HOME I INSERT J K KP0 KP1 KP2 KP3 KP4 KP5 KP6 KP7 KP8 KP9 KPASTERISK KPDOT KPMINUS KPPLUS KPSLASH L LEFT LEFTALT LEFTBRACE LEFTCTRL LEFTSHIFT M MEXTRA MINUS MLEFT MMIDDLE MRIGHT MSIDE N NEXTSONG NUMLOCK O P PAGEDOWN PAGEUP PLAYPAUSE PREVIOUSSONG Q R RIGHT RIGHTALT RIGHTBRACE RIGHTCTRL RIGHTSHIFT S SCROLLLOCK SEMICOLON SLASH SPACE T TAB U UP V W X Y Z
1589961261 DEBUG  : Registering USB hotplug callbacks
1589961261 INFO  : Waiting for device to show up ...
1589961269 INFO  : USB device connected
1589961269 DEBUG  : Interface successfully claimed
1589961269 INFO  : USB device found during enumeration
1589961269 INFO  : USB device connected
1589961269 DEBUG  : USB Event wakeup with 1 devices registered
1589961269 INFO  : Setting up device 
libusb: error [udev_hotplug_event] ignoring udev action bind
Erreur de segmentation
[nihil@ghost rules.d]$ uname -a
Linux ghost 5.6.12-1-MANJARO #1 SMP PREEMPT Sun May 10 14:36:43 UTC 2020 x86_64 GNU/Linux
`
Best regards.

**Comment by khampf** [comment]
I uploaded my binary package g13-git-v1.0.3.beta.r1.g2b39aec-3-x86_64.pkg.tar.xz for archlinux (should work on manjaro as is I hope), can you please try to install it from the [releases](/khampf/g13/releases) page and see if you get the same results? That way we can rule out errors introduced by building the package in your environment.

If this makes no difference, the next step would be to generate a core-dump from a crash and upload it so that I can analyze it with a debugger. Core dumps can be enabled using the `ulimit` command but I am not completely sure how to make that stick when running stuff with sudo but we can figure it out.

**Comment by nihilman** [comment]
Same problem with your binary.
Here is the core-dump file with your binary.
[core.g13d.966.5e497bab2a1a48b08f31ca99ae63cfaf.1618.1589972277000000000000.lz4.tar.gz](https://github.com/khampf/g13/files/4656351/core.g13d.966.5e497bab2a1a48b08f31ca99ae63cfaf.1618.1589972277000000000000.lz4.tar.gz)
I have tried to unplug all my péripheral in case of a concflict but it did nothing better!

**Comment by khampf** [comment]
It was close to perfect - only that I forgot debug symbols are not included by default so I made an archive [g13d-v1.0.3-beta-1-g2b39aec-debugbins-x86_64.tar.xz](https://github.com/khampf/g13/releases/download/v1.0.3-beta/g13d-v1.0.3-beta-1-g2b39aec-debugbins-x86_64.tar.xz) that includes the binaries with debugging symbols enabled. Can you temporarily rename /usr/bin/g13d to something and put the debug binary in its place and do the exact same thing once more?

I felt this is a quick and easy way of getting further but I can build a complete debug-package for arch/manjaro that installs normally instead of handing out the binaries if you want me to.

**Comment by nihilman** [comment]
Good morning,
here is the file : 
[core.g13d.966.2ea90a20035d470ab51f77f138c89d9b.1503.1590046236000000000000.lz4.tar.gz](https://github.com/khampf/g13/files/4661133/core.g13d.966.2ea90a20035d470ab51f77f138c89d9b.1503.1590046236000000000000.lz4.tar.gz)
I hope I did it correctly.
I've tried the runtest binary (plugged and unplugged) and it say the same resul:
`[nihil@ghost debug info g13]$ runtests 
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from G13Key
[ RUN      ] G13Key.g13_key_maps_to_value
[       OK ] G13Key.g13_key_maps_to_value (0 ms)
[----------] 1 test from G13Key (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1 ms total)
[  PASSED  ] 1 test.
`

**Comment by khampf** [comment]
Good work! Now I can see what happened and it looks like libusb crashed on a timeout when the g13d binary was initializing the LCD and sending the logo to the device. Does the G13 logo show on the LCD? Anyways, what version of libusb do you have? (`pacman -Q libusb`)

The _runtests_ binary just runs a couple of tests on a component included in _g13d_ so it will most likely always run successfully at this point (there is only a keymap lookup test implemented so far).

As the latest major change was support for hotplugging, I could add a parameter to disable hotplugging and use the old code for looking up devices once on start instead. I will try to build another debuggable binary for you sometime today.

**Comment by nihilman** [comment]
I see the "G13" original logo only not the GNU logo.
`[nihil@ghost Bureau]$ pacman -Q libusb
libusb 1.0.23-2`

**Comment by nihilman** [comment]
Trying to plug -unplug several times  and editing dmesg after:
g13d[1575]: segfault at 7ffd401efff0 ip 00007f7b11db5af7 sp 00007ffd401efff0 error 6 in libusb-1.0.so.0.2.0[7f7b11db5000+d000]
g13d[1989]: segfault at 7fff5f4dafb0 ip 00007fdb75ebd446 sp 00007fff5f4dafa0 error 6 in libc-2.31.so[7fdb75e59000+14c000]
g13d[2078]: segfault at 7ffd84d67fe8 ip 00007f62cb4a2ae5 sp 00007ffd84d67fd0 error 6 in libusb-1.0.so.0.2.0[7f62cb4a2000+d000]
g13d[2154]: segfault at 7ffdaa0b4fd8 ip 00005588e276827f sp 00007ffdaa0b4fd0 error 6 in g13d[5588e2750000+27000]

If it can help.

**Comment by khampf** [comment]
If you start g13d before plugging in the device, does it crash before you plug it in?

You have the same libusb version as I do and the crashes are happening inside libusb as your debugging states as well as my analysis of the core dump. However, without also building a debuggable libusb and keeping identical binaries for that around it is hard to see why.

I made another binary where I disabled hotplugging - can you try it and send me the core dump again if it crashes? [g13d-v1.0.3-beta-1-g2b39aec-dirty-debug-nohot.tar.xz](https://github.com/khampf/g13/releases/download/v1.0.3-beta/g13d-v1.0.3-beta-1-g2b39aec-dirty-debug-nohot.tar.xz). This version can not detect you plugging in the device at all so the first question is only regarding the previous binary.

**Comment by nihilman** [comment]
no logs after reboot with the g13 unplugged.
`nihil@ghost ~]$ systemctl status g13
● g13.service - Logitech G13 daemon
     Loaded: loaded (/usr/lib/systemd/system/g13.service; static; vendor preset>
     Active: inactive (dead)`
Try the binary in the next post.

**Comment by nihilman** [comment]
Sorry but it don't work too.
[core.g13d.966.9d0bc097f22b47c09ae14141fe1a6b5a.912.1590128609000000000000.lz4.tar.gz](https://github.com/khampf/g13/files/4666427/core.g13d.966.9d0bc097f22b47c09ae14141fe1a6b5a.912.1590128609000000000000.lz4.tar.gz)

If I am the only in this case, don't waste your time for me, I can play with the old version. If you want to continu for your skill,  no problem I will be your beta tester.

**Comment by khampf** [comment]
I would like to continue to investigate as it seems that there is something going wrong with the LCD and that is code I think I have not changed in any way relevant to this. Not many people use this driver, you might be the only one (besides me) who run the latest version.

I will look at the code and go trough the InitLcd() parts and see what is going on and get back here with any findings.

**Comment by nihilman** [comment]
Ok, I wait your feedback.
Good luck!

**Comment by khampf** [comment]
I fixed some bugs and released v1.0.4 - can you try it out and see if there is any change for you? It is released in the AUR but also available as prebuild (non-debuggable) package here on the projects github release page.
(If it still crashes I will make another debuggable binary and we will try again).

**Comment by nihilman** [comment]
Good news !!!! It work.
Quickly tested , my binds are working fine.
Thank you. Have a nice day.

**Comment by khampf** [comment]
Seems to have ironed out the bugs that caused the problems you had, I will close this issue. Thank you for your help with debugging and testing!
