### ISSUE TITLE
Compiling on Debian requires pthread

### ISSUE THREAD

**Issue by dhallgb** [khampf/g13#4]
Thanks for your efforts in refactoring. When running the make command on Ubuntu 20.04 the linker stopped with error message `undefined reference to symbol 'pthread_getspecific@@GLIBC_2.2.5'`. This indicated a missing reference to the pthread library.

My way around that was to add pthread explicitly into the compiler flags in the CMakeList.txt file.
```c++
set(CMAKE_CXX_FLAGS "-std=c++17 -pthread")
```

This completed successfully and runs well.

**Comment by khampf** [comment]
Hmm. I thought I removed dependencies on pthread after using a separate thread in a bughunt. Might have forgotten one - will check that when time permits.

**Comment by khampf** [comment]
Should be fixed by commit a02223cbfc1b32eb8df37acf5dfabbcff0eea64b
