### ISSUE TITLE
Issues with libinput 1.15.902

### ISSUE THREAD

**Issue by banduccm** [khampf/g13#6]
I'm using g13d on Fedora 32. I was running a version I built myself from back in March, and today it stopped working. I was unable to get keypress events in Gnome, but using 'showkey' I could see that the proper key events were being sent. When I switched to a VT, g13d worked as expected - I saw the correct output on the terminal. I went back through my update history and saw that libinput updated to libinput-1.15.902-1.fc32.x86_64. I rolled back the update (to libinput 1.15.4) and g13d started working again.

I see the same behavior with your latest release binary (1.0.4).

Curiously, I'm getting a core dump when I try to build your latest g13d master branch against libinput-devel-1.15.902-1.fc32.x86_64. I'm going to try to dig into that a bit more and see if I can learn anything, but I'm new to Linux development, so it may take me a bit.

Please let me know if there's anything I can do to be helpful here or if there are more details I can provide.

Thank you!

System:
Fedora 32, Kernel 5.7.11-200.fc32.x86_64

**Comment by banduccm** [comment]
I think I was able to get a trace. If this is useful, I'd be happy to provide a core dump as well:
```
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:440
#1  0x00007f8fb0cc7726 in std::char_traits<char>::copy (__n=16926440, __s2=0x10246e8 "", __s1=<optimized out>)
    at /usr/src/debug/gcc-10.2.1-1.fc32.x86_64/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/char_traits.h:395
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy (__n=16926440, __s=0x10246e8 "", __d=<optimized out>)
    at /usr/src/debug/gcc-10.2.1-1.fc32.x86_64/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:351
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy (__n=16926440, __s=0x10246e8 "", __d=<optimized out>)
    at /usr/src/debug/gcc-10.2.1-1.fc32.x86_64/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:346
#4  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars (__k2=<optimized out>, __k1=0x10246e8 "", 
    __p=<optimized out>) at /usr/src/debug/gcc-10.2.1-1.fc32.x86_64/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:393
#5  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (this=0x7ffda949ebd0, __beg=0x10246e8 "", 
    __end=<optimized out>)
    at /usr/src/debug/gcc-10.2.1-1.fc32.x86_64/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.tcc:225
#6  0x000000000041d63a in G13::G13_Manager::getStringConfigValue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#7  0x000000000041d80c in G13::G13_Manager::MakePipeName[abi:cxx11](G13::G13_Device*, bool) ()
#8  0x000000000040b017 in G13::G13_Device::RegisterContext(libusb_context*) ()
#9  0x0000000000419a8e in G13::G13_Manager::SetupDevice(G13::G13_Device*) ()
#10 0x000000000041e620 in G13::G13_Manager::Run() ()
#11 0x000000000041c7d9 in main ()
```

**Comment by banduccm** [comment]
I did some debugging and I can confirm that the crash I'm seeing has nothing to do with the libinput issue.

I rebuilt a working version locally with libinput 1.15.902 and I still have the same lack of input problems. Rolling back to 1.15.4 makes it work again. I'm guessing this is a libinput problem, but I'll have to learn more about how g13d interfaces with libinput to see if it's something that needs to change here, or a bug that should be reported upstream.

**Comment by khampf** [comment]
As Arch Linux is currently using 1.15.6 I could try recompiling against that library version but I use my g13d daily and I seem not to experience the same issues. But do follow up if you have the time, it could potentially stop a bug from coming at me in the future :-)

**Comment by banduccm** [comment]
Fedora updated to libinput 1.16 today (libinput-1.16.0-1.fc32.x86_64), and g13d appears to be working perfectly. I'll let you know if I run into any other issues, but for now, things look good!
