### ISSUE TITLE
stickzone issues

### ISSUE THREAD

**Issue by TheHermit1017** [khampf/g13#8]
When I press the stick left or right it works as intended, but I have to feather the stick forward or backwards for my character to move forward or backwards. But, when I press the stick all the way forwards or backwards nothing happens. I believe it has something to do with the active stickzones STICK_PAGEUP   { 0 x 0 / 1 x 0.1 }   SEND KEYS: PAGEUP and  STICK_PAGEDOWN   { 0 x 0.9 / 1 x 1 }   SEND KEYS: PAGEDOWN being included in my active stickzone configuration. How do I remove those active stick zones from my configuration file if that is in fact the issue?

**Comment by khampf** [comment]
I have never thought of testing key repeats. I will try to investigate later but try to comment out and switch around (switching the settings for the axis to something else just to see if it also happens on letter keys and more)

**Comment by nihilman** [comment]
Just bind your keys like this :

bind STICK_LEFT KEY_A
bind STICK_RIGHT KEY_D
bind STICK_UP KEY_W
bind STICK_PAGEUP KEY_W
bind STICK_DOWN KEY_S
bind STICK_PAGEDOWN KEY_S

works for me

**Comment by TheHermit1017** [comment]
I tried this before but must not have bound the keys correctly. Everything is working perfectly now. Thank you for the assistance!

**Comment by nihilman** [comment]
You're welcome.

**Comment by tmackay** [comment]
Another way is to remove the extra zones entirely to avoid sending the key twice:
```
stickzone del STICK_PAGEUP
stickzone del STICK_PAGEDOWN
stickzone bounds STICK_UP 0 0 1 0.2
stickzone bounds STICK_DOWN 0 0.8 1 1
```
